name: flutter_myinsta
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  fluttertoast:
  image_picker:
  cached_network_image:
  eva_icons_flutter:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  platform_device_id:
  firebase_messaging:
  flutter_local_notifications: ^9.4.0
  shared_preferences:
  logger:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
